In [2]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
V_data = [1.,2.,3.]
V = torch.Tensor(V_data)
print(V)

tensor([ 1.,  2.,  3.])


In [4]:
M = [[1.,2.,3.],[4.,5.,6.]]
M = torch.Tensor(M)
print(M)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])


In [5]:
T_data = [[[1.,2.],[3.,4.]],[[5.,6.],[7.,8.]]]
T = torch.Tensor(T_data)
print(T)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]]])


In [6]:
print(T[0][1][1])

tensor(4.)


In [7]:
x = torch.randn(3,4,5)
x

tensor([[[ 0.5431, -1.2956, -0.4681,  0.8674, -1.0671],
         [-0.2257,  1.9390,  0.5736,  0.7181, -0.8138],
         [ 0.7730, -0.1040,  1.5151,  1.4084,  0.5299],
         [-1.3353,  1.4416,  0.4625,  0.7972, -0.1488]],

        [[ 0.3746, -0.6750,  0.0336,  0.7138,  2.2252],
         [ 0.1328,  0.1231, -0.2180,  1.1797,  0.3777],
         [ 0.2926,  0.7864, -0.0342, -1.3068,  0.5694],
         [-0.0596, -0.3087, -0.0857,  0.8599,  1.6077]],

        [[ 0.5246,  0.5291, -0.0770,  0.3224,  0.4370],
         [-1.8931, -0.5044,  1.4705, -0.9269, -0.2306],
         [-0.8672,  1.1268, -1.8941,  1.8757,  0.6530],
         [-0.0440,  1.3589,  0.0806,  0.8197, -1.1764]]])

In [8]:
y = torch.randn(3,4,5)

In [9]:
z = torch.cat([x,y])
z.shape

torch.Size([6, 4, 5])

In [10]:
print(z.view(20,6))

tensor([[ 0.5431, -1.2956, -0.4681,  0.8674, -1.0671, -0.2257],
        [ 1.9390,  0.5736,  0.7181, -0.8138,  0.7730, -0.1040],
        [ 1.5151,  1.4084,  0.5299, -1.3353,  1.4416,  0.4625],
        [ 0.7972, -0.1488,  0.3746, -0.6750,  0.0336,  0.7138],
        [ 2.2252,  0.1328,  0.1231, -0.2180,  1.1797,  0.3777],
        [ 0.2926,  0.7864, -0.0342, -1.3068,  0.5694, -0.0596],
        [-0.3087, -0.0857,  0.8599,  1.6077,  0.5246,  0.5291],
        [-0.0770,  0.3224,  0.4370, -1.8931, -0.5044,  1.4705],
        [-0.9269, -0.2306, -0.8672,  1.1268, -1.8941,  1.8757],
        [ 0.6530, -0.0440,  1.3589,  0.0806,  0.8197, -1.1764],
        [ 1.0229, -0.6546, -0.7756,  0.1010, -2.9044,  0.7951],
        [ 1.3056,  1.4233, -0.4405, -1.0838,  0.7521, -0.5250],
        [-1.4369,  1.8602,  0.0416,  1.8228,  0.0137,  1.1245],
        [ 0.7639, -0.6786, -0.2294,  1.1256,  1.3904,  0.4277],
        [ 2.3831,  0.5883,  0.0182, -0.3897,  0.4537,  0.6084],
        [-1.1868,  0.8026, -0.0947,  0.0

In [24]:
x = torch.randn((1,3),requires_grad = True)
#print(x)
y = torch.randn((1,3), requires_grad = True)
z = x * y
s = z.sum()
s.grad_fn
s.backward()
print(z.grad)

None


In [25]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)
# By default, user created Tensors have ``requires_grad=False``
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)

# ``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
# flag in-place. The input flag defaults to ``True`` if not given.
x = x.requires_grad_()
y = y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)

# Now z has the computation history that relates itself to x and y
# Can we just take its values, and **detach** it from its history?
new_z = z.detach()

# ... does new_z have information to backprop to x and y?
# NO!
print(new_z.grad_fn)
# And how could it? ``z.detach()`` returns a tensor that shares the same storage
# as ``z``, but with the computation history forgotten. It doesn't know anything
# about how it was computed.
# In essence, we have broken the Tensor away from its past history

False False
None
True
None


** Affine maps **

In [31]:
lin = nn.Linear(5,3)
data = torch.randn(2,5)
lin(data)

tensor([[ 0.3488,  0.3756,  0.3832],
        [ 0.7868,  0.9429, -0.2002]])

In [33]:
data = torch.randn(2,3)
data

tensor([[ 0.7928,  1.1799,  0.5760],
        [-0.1716,  0.8839, -0.2836]])

In [34]:
F.relu(data)

tensor([[ 0.7928,  1.1799,  0.5760],
        [ 0.0000,  0.8839,  0.0000]])

In [46]:
data = torch.randn(1,5)
data

tensor([[ 2.0894,  0.4378, -0.1655, -0.3901,  0.2640]])

In [48]:
F.softmax(data, dim=1)

tensor([[ 0.6487,  0.1244,  0.0680,  0.0543,  0.1045]])

In [49]:
F.log_softmax(data, dim=1)

tensor([[-0.4328, -2.0844, -2.6877, -2.9124, -2.2583]])